name: build and test
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  build_and_test:
    name: "Build and Test on os: ${{ matrix.os }}. dotnet SDK version: ${{ matrix.dotnet }}"
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        dotnet: ['6.0.x']
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: dotnet restore 
        run: dotnet restore

      - name: dotnet tool restore
        run: dotnet tool restore

      - name: Build with dotnet (debug)
        run: |
          dotnet build --configuration Debug NLoop.Server

      - name: Run Domain test in ${{ matrix.os }} (Debug)
        run: dotnet test tests/NLoop.Domain.Tests

      - name: Run property test in ${{ matrix.os }} (Debug)
        run: dotnet run --project tests/NLoop.Server.PropertyTests

      - name: Run unit tests for the server (Debug)
        run: dotnet test tests/NLoop.Server.Tests --filter="Docker!=On"
      - name: Build with dotnet (Release)
        run: |
          dotnet build --configuration Release NLoop.Server

      - name: Run Domain test in ${{ matrix.os }} (Release)
        run: dotnet test --configuration Release tests/NLoop.Domain.Tests

      - name: Run property test in ${{ matrix.os }} (Release)
        run: dotnet run --project tests/NLoop.Server.PropertyTests --configuration Release

      - name: Run unit tests for the server (Release)
        run: dotnet test --configuration Release tests/NLoop.Server.Tests --filter="Docker!=On"
